name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Nix Flake Check
        shell: bash
        run: |
          nix flake check
